LibraryDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('library.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

library/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='library'
urlpatterns = [
    path('cateview/<int:category_id>',views.cate_view, name="view"),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('index/',views.index, name="index"),
]

library/models.py
import pymsgbox
from datetime import datetime
import uuid
from django.db import models
from django.urls import reverse
from django.utils import timezone

from django.utils.html import mark_safe
STATUS_CHOICES = (
        ('-', '--------'),
        ('a', 'Đang mượn'),
        ('d', 'Đã trả'),
    )

class Category(models.Model):
    name_cate = models.CharField(max_length=100)

    def __str__(self):
        return self.name_cate


class Author(models.Model):
    name_author = models.CharField(max_length=50)

    def __str__(self):
        return self.name_author


class Book(models.Model):
    #Fields
    status = models.BooleanField(default=1)
    name_book = models.CharField(max_length=100)
    quantity_book = models.IntegerField(default=1)
    cate = models.ManyToManyField(Category)
    author = models.ManyToManyField(Author)
    description = models.TextField(null=True,max_length = 1000)
    image = models.ImageField(upload_to='./img', default='./img/default.png')

    def get_status(self):
            if self.quantity_book >= 1:
                return self.status == 1
            else:
                return self.status == 0

    # def check_quantity(self):
    #     if BorrowBook.book == True:
    #         return self.quantity_book - 1
    #     self.quantity_book.save()


    @property
    def image_preview(self):
        if self.image:
            return mark_safe('<img src="{}" width="50" height="75" />'.format(self.image.url))
        return ""

    def get_authors(self):
        return ",".join([str(p) for p in self.author.all()])

    def get_cates(self):
        return ",".join([str(p) for p in self.cate.all()])

    def __unicode__(self):
        return "{0}".format(self.name_book)

    def __str__(self):
        return self.name_book


class Borrower(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=12)
    cmnd = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class BorrowBook(models.Model):
    borrower = models.ForeignKey(Borrower, on_delete=models.CASCADE)
    book = models.ForeignKey(Book ,on_delete=models.CASCADE)
    status = models.CharField(max_length=50,choices=STATUS_CHOICES,default='-')
    borrow_date = models.DateTimeField(null=True)
    due_back = models.DateTimeField(null=True)

    a= 'Trễ hạn'
    b = 'Chưa tới hạn'

    def set_statuss(self):
        now = timezone.now()
        if self.due_back <= now:
            return self.a
        else:
            return self.b

    def check_available(self):
        if Book.quantity_book != 0:
            return self.book.quantity_book

    def __str__(self):
        return f'{self.id} ({self.book.name_book})'

    def save(self, *args, **kwargs):
        # b = BorrowBook.objects.get(self)
        if (Book.objects.get(id=self.book_id).quantity_book == 0):
            return pymsgbox.alert('Sách Đã Được Mượn Hết!', 'Thông Báo')
        elif(Book.objects.get(id=self.book_id).quantity_book >= 1):
            c = Book.objects.get(id=self.book_id).quantity_book
            c -= 1
            Book.objects.select_related().filter(id=self.book_id).update(quantity_book=c)
        super().save(*args, **kwargs)

library/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.http import HttpResponse
from .models import Category, Book, Borrower, BorrowBook, Author
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def index(request):
    bookitem = Book.objects.all()
    cateitem = Category.objects.all()

    paginator = Paginator(bookitem,3)
    page_Number = request.GET.get('page',1)
    try:
        bookpage = paginator.page(page_Number)
    except PageNotAnInteger:
        bookpage = paginator.page(1)
    except EmptyPage:
        bookpage = paginator.page(paginator.num_pages)

    context ={
        'book' : bookitem,
        'category' : cateitem,
        'paging' : bookpage,
        'cateview':cate_view,
    }
    return render(request, "library/index.html",context)


def cate_view(request, category_id):
    cate_view= Category.objects.get(pk = category_id)
    cateitem = Category.objects.all()
    bookitem2 = Book.objects.all()

    paginator = Paginator(bookitem2, 3)
    page_Number = request.GET.get('page', 1)
    try:
        bookpage2 = paginator.page(page_Number)
    except PageNotAnInteger:
        bookpage2 = paginator.page(1)
    except EmptyPage:
        bookpage2 = paginator.page(paginator.num_pages)

    context1={
        'cate':cate_view,
        'catename': cateitem,
        'paging2': bookpage2,
    }
    return render(request, "library/cateview.html", context1)

from django.views import generic

class BookDetailView(generic.DetailView):
    """Generic class-based detail view for a book."""
    model = Book
    template_name = "library/book_detail.html"
    
    def get_context_data(self, *args, **kwargs):
        context = super(BookDetailView,     self).get_context_data(*args, **kwargs)
        context['books'] = Book.objects.all()

        return context

# def book_detail_view(request, book_id, cate):
#     bookitem = Book.objects.all()
#     book_view = Book.objects.get(pk=book_id)
#     cate_view= Category.objects.get(pk = category_id)
#     cateitem = Category.objects.all()

#     context ={
#         'bookview': book_view,
#         'book' : bookitem,
#         'category' : cateitem,
#         'paging' : bookpage,
#         'cateview':cate_view,
#     }
#     return render(request, 'library/book_detail.html', context)
    
# def book_view(request, book_id, category_id):
#     book_view= Book.objects.get(pk = book_id)
#     bookitem3 = Book.objects.all()
#     cate_view= Category.objects.get(pk = category_id)
#     cateitem = Category.objects.all()

#     context2={
#         'book' : bookitem,
#         'bookview': book_view,
#         'cateview':cate_view,
#         'catename': cateitem,
#     }
#     return render(request, "library/bookview.html", context2)

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="icon" href="/media/img/library.ico">
  <title>My Libary</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <header>
    <div class="collapse bg-dark" id="navbarHeader">
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
      <div class="container d-flex justify-content-between">
        <a href="{% url 'library:index' %}" class="navbar-brand d-flex align-items-center">
          <img src="/media/img/book.png" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
            stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
          <strong>My Libary</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>
  <div class="noidung">
    {% block content %}

    {% endblock %}
  </div>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>
</body>

library/templates/library/book_detail.html
{% extends 'library/base.html' %}
{% block content %}

<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4">{{ book.name_book }}</h1>

      <!-- Author -->
      <p class="lead">
        Tác giả:
        <a href="#">{{ book.author.all|join:", " }}</a>
      </p>

      <!-- <hr> -->

      <!-- Genre -->
      <p>Thể loại: <a href="#">{{ book.cate.all|join:", " }}</a></p>

      <hr>

      <!-- Quantity -->
      <p>Số lượng: {{ book.quantity_book }}</p>

      <hr>

      <!-- Preview Image -->
      <img class="img-fluid rounded" src={{book.image.url}} alt="" height="600" width="300">

      <hr>

      <p>{{ book.description }}</p>

      <hr>

      <!-- Regist the book -->
      <div class="card my-4">
        <h5 class="card-header">Đăng ký để mượn sách: </h5>
        <div class="card-body">
          <form>

            <button type="submit" class="btn btn-primary">Mượn ngay</button>
          </form>
        </div>
      </div>
    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">
      
      <!-- Search Widget -->
      <!-- <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div> -->

      <!-- Categories Widget -->
      <div style="text-align: center;">
      <div class="card my-4">
        <h5 class="card-header">Sách cùng thể loại {{ book.cate.all|join:", " }}</h5>
        <div class="card-body">
          <div class="row justify-content-md-center">
            <div class="col-lg-8">
              <!-- <ul class="list-unstyled mb-0"> -->
                
                {% for book in books %}
                  {{book.name_book}} 
                  <img class="img-fluid rounded" src={{book.image.url}} alt="" >
                  <hr>
                {% endfor %}

              <!-- </ul> -->
            </div>
          </div>
        </div>
      </div>
    </div>


    </div>

  </div>
  <!-- /.row -->

</div>

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}

library/templates/library/cateview.html
{% extends 'library/base.html' %}
{% block content %}
<main role="main" xmlns="http://www.w3.org/1999/html">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Danh Mục Sách</h1>
            <p>
                <a href="{% url 'library:index' %}" class="btn btn-primary my-2">Xem Tất Cả</a>
                {% for item in catename %}
                <a href="{% url 'library:view' item.id %}" class="btn btn-primary my-2">{{ item.name_cate }}</a>
                {% endfor %}
            </p>
        </div>
    </section>
</main>
<div class="album bg-light">
    <div class="container">
        <div class="row">
            {% if cate %}
            {% for item in cate.book_set.all %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{ item.image.url }}" height="400">
                    <div class="card-body">
                        <p class="card-text">{{ item.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'library:book_detail' item.id %}"
                                    class="btn btn-outline-secondary">Thông tin thêm</a>
                                <a href="#" class="btn btn-outline-secondary">Mượn sách</a>
                            </div>
                        </div>
                        <small class="number">Số lượng: {{ item.quantity_book }}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <ul class="pagination">
            {% if paging2.has_previous %}
            <a class="page-link" href="?page={{ paging2.previous_page_number }}"><b>Previous</b></a>
            {% endif %}

            {% if cate %}
            {% for i in paging2.paginator.page_range %}
            {% if cate.book_set.all.paging2.number == i %}
            <li class="page-item"><a class="page-link" href="#">{{ i }}</a></li>
            {% else %}
            <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% endif %}

            {% if paging2.has_next %}
            <a class="page-link" href="?page={{ paging2.next_page_number }}"><b>Next</b></a>
            {% endif %}
        </ul>
    </div>
</div>
{#    <footer class="text-muted">#}
{#      <div class="container">#}
{#        <p class="float-right">#}
{#          <a href="#">Back to top</a>#}
{#        </p>#}
{#      </div>#}
{#    </footer>#}
{% endblock %}

library/templates/library/index.html
{% extends 'library/base.html' %}
{% block content %}
<main role="main" xmlns="http://www.w3.org/1999/html">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Danh Mục Sách</h1>
      <p>
        <a href="{% url 'library:index' %}" class="btn btn-primary my-2">Xem Tất Cả</a>
        {% for item in category %}
        <a href="{% url 'library:view' item.id %}" class="btn btn-primary my-2">{{ item.name_cate }}</a>
        {% endfor %}
      </p>
    </div>
  </section>
</main>
<div class="album bg-light">
  <div class="container">
    <div class="row">
      {% for item in paging %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" src="{{ item.image.url }}" height="400">
          <div class="card-body">
            <p class="card-text">{{ item.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'library:book_detail' item.id %}" class="btn btn-outline-secondary">Thông tin thêm</a>
                <a href="#" class="btn btn-outline-secondary">Mượn sách</a>
              </div>
            </div>
            <small class="number">Số lượng: {{ item.quantity_book }}</small>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="container">
    <ul class="pagination">
      {% if paging.has_previous %}
      <a class="page-link" href="?page={{ paging.previous_page_number }}"><b>Previous</b></a>
      {% endif %}

      {% for i in paging.paginator.page_range %}
      {% if paging.number == i %}
      <li class="page-item"><a class="page-link" href="#">{{ i }}</a></li>
      {% else %}
      <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}

      {% if paging.has_next %}
      <a class="page-link" href="?page={{ paging.next_page_number }}"><b>Next</b></a>
      {% endif %}
    </ul>
  </div>


</div>
{#    <footer class="text-muted">#}
{#      <div class="container">#}
{#        <p class="float-right">#}
{#          <a href="#">Back to top</a>#}
{#        </p>#}
{#      </div>#}
{#    </footer>#}
{% endblock %}